<?php
/*
 * update.php
 * 
 * Copyright 2015 Jim <jim@noideersoftware.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 * Purpose :- update settings.php 
 */
 define('DOC_ROOT', realpath(dirname(__FILE__) . '/../'));
 require DOC_ROOT.'/includes/master.inc.php'; // do login or not
 $settings = $site->settings;
 if(!$_POST) {redirect($ite->settings['url'].'/index.php');}
 	foreach ($_POST as $key => $tzitem)
 	{
		// modify the array
		$settings[$key] = $tzitem;
		
	}
	$file = DOC_ROOT.'/includes/settings.php';
	$name = 'settings';
	$header ="SETTINGS v". $settings['version']."\n do not edit this file ! use admin cp unless told otherwise";
	writeini ($settings,$file,$header,$name);
	//unset($site->settings);
	$site->settings= $settings;
	echo "<br>new settings<br>";
	print_r($site->settings);
	//die('<br>ready to redirect');
	
	redirect('/admin.php');
?>
